def configure_modules(
    ex,
    cm,
    cdm,
    pdm,
    sm,
    im,
    mm,
    rm,
    am,
    scm,
    se,
    *,
    log_debug,
    log_info,
    get_db,
    backup_catalog_db,
    validate_destination_path,
    sanitize_folder_name,
    export_state,
    AppState,
    EXPORT_HISTORY_PATH,
    IMAGE_EXTENSIONS,
    RUNTIME_DIR,
    DATA_DIR,
    CATALOG_DIR,
    catalog_db_path,
    sanitize_catalog_name,
    APP_VERSION,
    get_blur_label,
    load_quality_settings,
    sqlite3,
    APP_NAME,
    BACKUP_DIR,
    get_face_engine_device,
    get_face_engine_gpu_error,
    get_embedding_cache,
    app_settings,
    save_app_settings,
    set_app_settings,
    get_blur_info,
    THUMB_CACHE_DIR,
    quiet_external_output,
    FAISS_AVAILABLE,
    get_faiss_index,
    get_ref_ids,
    save_quality_settings,
    qa_clear_memory_caches,
    qa_clear_disk_caches,
    clear_embedding_cache,
    manual_search_state,
    quality_audit_state,
    get_scan_checkpoint,
    save_scan_checkpoint,
    clear_scan_checkpoint,
    min_face_area,
    ref_match_threshold,
    load_embedding_disk_cache,
    save_embedding_disk_cache,
    face_det_size,
    scan_state,
    automation,
):
    ex.configure(
        log_debug=log_debug,
        log_info=log_info,
        get_db=get_db,
        backup_catalog_db=backup_catalog_db,
        validate_destination_path=validate_destination_path,
        sanitize_folder_name=sanitize_folder_name,
        export_state=export_state,
        get_current_catalog=lambda: AppState.current_catalog,
        export_history_path=EXPORT_HISTORY_PATH,
        image_extensions=IMAGE_EXTENSIONS,
        runtime_dir=RUNTIME_DIR,
        catalog_dir=CATALOG_DIR,
        thumb_cache_dir=THUMB_CACHE_DIR,
    )

    cm.configure(
        data_dir=DATA_DIR,
        catalog_dir=CATALOG_DIR,
        get_db=get_db,
        catalog_db_path=catalog_db_path,
        sanitize_catalog_name=sanitize_catalog_name,
        get_current_catalog=lambda: AppState.current_catalog,
        set_current_catalog=lambda value: setattr(AppState, "current_catalog", value),
    )

    cdm.configure(
        get_db=get_db,
        backup_catalog_db=backup_catalog_db,
        sanitize_catalog_name=sanitize_catalog_name,
        catalog_db_path=catalog_db_path,
        get_current_catalog=lambda: AppState.current_catalog,
        app_version=APP_VERSION,
    )

    pdm.configure(
        get_db=get_db,
        get_current_catalog=lambda: AppState.current_catalog,
        get_catalog_dir=lambda: CATALOG_DIR,
        get_blur_label=get_blur_label,
        load_quality_settings=load_quality_settings,
        sqlite3=sqlite3,
    )

    sm.configure(
        app_name=APP_NAME,
        app_version=APP_VERSION,
        data_dir=DATA_DIR,
        catalog_dir=CATALOG_DIR,
        thumb_cache_dir=THUMB_CACHE_DIR,
        backup_dir=BACKUP_DIR,
        scan_state=scan_state,
        export_state=export_state,
        face_engine_device=get_face_engine_device,
        face_engine_gpu_error=get_face_engine_gpu_error,
        load_export_history=ex.load_export_history,
        get_current_catalog=lambda: AppState.current_catalog,
        embedding_cache=get_embedding_cache(),
        app_settings=app_settings,
        save_app_settings=save_app_settings,
        set_app_settings=set_app_settings,
        get_db=get_db,
        automation=automation,
    )

    im.configure(
        app_settings=lambda: app_settings,
    )

    mm.configure(
        get_db=get_db,
        get_current_catalog=lambda: AppState.current_catalog,
        load_quality_settings=load_quality_settings,
        get_blur_info=get_blur_info,
        log_info=log_info,
        thumb_cache_dir=THUMB_CACHE_DIR,
        app_settings=app_settings,
        automation=automation,
    )

    rm.configure(
        backup_catalog_db=backup_catalog_db,
        get_db=get_db,
        get_current_catalog=lambda: AppState.current_catalog,
        catalog_dir=CATALOG_DIR,
        get_blur_info=get_blur_info,
        face_box_area=se.face_box_area,
        ensure_face_engine=se.ensure_face_engine,
        imread_unicode=se.imread_unicode,
        quiet_external_output=quiet_external_output,
        scanner_engine=se,
        faiss_available=FAISS_AVAILABLE,
        faiss_index=get_faiss_index,
        ref_ids=get_ref_ids,
        load_quality_settings=load_quality_settings,
        save_quality_settings=save_quality_settings,
        qa_clear_memory_caches=qa_clear_memory_caches,
        qa_clear_disk_caches=qa_clear_disk_caches,
        clear_embedding_cache=clear_embedding_cache,
        thumb_cache_dir=THUMB_CACHE_DIR,
        manual_search_state=lambda: manual_search_state,
    )

    am.configure(
        backup_catalog_db=backup_catalog_db,
        get_db=get_db,
        get_current_catalog=lambda: AppState.current_catalog,
        sanitize_catalog_name=sanitize_catalog_name,
        get_pendencies=mm.get_pendencies,
        explorer_entry_info=mm.explorer_entry_info,
        get_blur_info=get_blur_info,
        data_dir=DATA_DIR,
        automation=automation,
    )

    scm.configure(
        sanitize_catalog_name=sanitize_catalog_name,
        catalog_dir=CATALOG_DIR,
        image_extensions=IMAGE_EXTENSIONS,
        gpu_diagnostics=sm.gpu_diagnostics,
        scan_state=scan_state,
        quality_audit_state=quality_audit_state,
        app_state=AppState,
        log_info=log_info,
        scanner_engine=se,
        get_db=get_db,
        face_box_area=se.face_box_area,
    )

    se.configure(
        log_debug=log_debug,
        log_info=log_info,
        quiet_external_output=quiet_external_output,
        get_memory_info=sm.get_memory_info,
        get_db=get_db,
        catalog_dir=CATALOG_DIR,
        sanitize_catalog_name=sanitize_catalog_name,
        get_scan_checkpoint=get_scan_checkpoint,
        save_scan_checkpoint=save_scan_checkpoint,
        clear_scan_checkpoint=clear_scan_checkpoint,
        get_blur_info=get_blur_info,
        is_background_face=se.is_background_face,
        face_box_area=se.face_box_area,
        min_face_area=min_face_area,
        ref_match_threshold=ref_match_threshold,
        faiss_available=FAISS_AVAILABLE,
        runtime_dir=RUNTIME_DIR,
        data_dir=DATA_DIR,
        image_extensions=IMAGE_EXTENSIONS,
        scan_state=scan_state,
        quality_audit_state=quality_audit_state,
        app_state=AppState,
        load_embedding_disk_cache=load_embedding_disk_cache,
        save_embedding_disk_cache=save_embedding_disk_cache,
        det_size=face_det_size,
        thumb_cache_dir=THUMB_CACHE_DIR,
        base_reference_max_side=512,
    )
